### ISSUE TITLE
使用 Github Pages 部署

### ISSUE THREAD

**Issue by linonetwo** [DiamondYuan/wiki#1]
感谢你在 Notion Telegram 群里分享的你的这个解决方案。

我发现只要做一点小改动，就能使用 Github Pages 部署 Wiki 了。

见 [linonetwo/Meme-of-LinOnetwo/tree/1bc6024d105131611fd2838b296dbe5e35ca1fe7](https://github.com/linonetwo/Meme-of-LinOnetwo/tree/1bc6024d105131611fd2838b296dbe5e35ca1fe7)
一是加一个：
```
---
permalink: /index.html
---
```
在 Readme 的最上面，二是在 JS 脚本里，在每次提交前，把 HTML 文件都重命名为 `index.html` 即可。

**Comment by DiamondYuan** [comment]
> 感谢你在 Notion Telegram 群里分享的你的这个解决方案。
> 
> 我发现只要做一点小改动，就能使用 Github Pages 部署 Wiki 了。
> 
> 见 https://github.com/linonetwo/Meme-of-LinOnetwo
> 一是加一个：
> 
> ```
> ---
> permalink: /index.html
> ---
> ```
> 在 Readme 的最上面，二是在 JS 脚本里，在每次提交前，把 HTML 文件都重命名为 `index.html` 即可。


我自己用的东西其实不是这个，我是用 Gitlab + runner 。每次提交都构建一个docker 镜像，然后部署在自己服务器上。
