### ISSUE TITLE
跨平台自启动+混合私有内容和公开内容

### ISSUE THREAD

**Issue by linonetwo** [DiamondYuan/wiki#3]
非常感激你提供的这个解决方案，[我用了好一段时间](https://github.com/DiamondYuan/wiki/issues/1)，是这个方案真正让我开始使用 tiddlywiki。

要不是看到这个方案，我可能一直都不会开始使用 tiddlywiki ，毕竟能保存备份到 github （并去抖，不要一直保存浪费流量）是我觉得很基本的一个功能。

![275851587101059_ pic_hd](https://user-images.githubusercontent.com/3746270/79535168-3f6d9600-80af-11ea-8739-6841bfbb2c1e.jpg)

同步到 Github +不用手动管理 HTML 文件就是一个「基本型需求」，此前我就知道 tiddlywiki 满足了许多「期望型需求」，但一直无法说服我开始用。（[KANO模型](https://wiki.mbalib.com/wiki/KANO%E6%A8%A1%E5%9E%8B)）

---

基于你的这个方案，我最近魔改出了 windows 和 Linux 上也能用，而且能把私有内容放一部分到 github 私有仓库里，并部署公开内容到 now.sh 上的方案 https://github.com/linonetwo/Tiddlywiki-NodeJS-Github-Template

我自己的 https://wiki.onetwo.ren https://github.com/linonetwo/Meme-of-LinOnetwo 也切换到这个方案了。

我写了一篇文章 [用TiddlyWiki替代Notion和EverNote作为个人知识管理系统](https://onetwo.ren/%E7%94%A8tiddlywiki%E6%9B%BF%E4%BB%A3notion%E5%92%8Cevernote%E7%AE%A1%E7%90%86%E7%9F%A5%E8%AF%86/) 来介绍我是怎么做的。

总之你的这个方案是我的起点，再次表达我的感谢！

**Comment by linonetwo** [comment]
![Screen Shot 2020-04-17 at 1 36 55 PM](https://user-images.githubusercontent.com/3746270/79535713-d8e97780-80b0-11ea-943b-68de0a4bfd1b.png)

看群聊记录是 2019-04-19 你推荐给我的，到现在差不多刚好一年呀。

**Comment by DiamondYuan** [comment]
我其实也是部署在 now.sh 上面的。
先关了。
